/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrderItemLedgerService } from "../orderItemLedger.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OrderItemLedgerCreateInput } from "./OrderItemLedgerCreateInput";
import { OrderItemLedgerWhereInput } from "./OrderItemLedgerWhereInput";
import { OrderItemLedgerWhereUniqueInput } from "./OrderItemLedgerWhereUniqueInput";
import { OrderItemLedgerFindManyArgs } from "./OrderItemLedgerFindManyArgs";
import { OrderItemLedgerUpdateInput } from "./OrderItemLedgerUpdateInput";
import { OrderItemLedger } from "./OrderItemLedger";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OrderItemLedgerControllerBase {
  constructor(
    protected readonly service: OrderItemLedgerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OrderItemLedger",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OrderItemLedger })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: OrderItemLedgerCreateInput
  ): Promise<OrderItemLedger> {
    return await this.service.create({
      data: {
        ...data,

        orderItem: {
          connect: data.orderItem,
        },
      },
      select: {
        amount: true,
        createdAt: true,
        id: true,
        orderId: true,

        orderItem: {
          select: {
            id: true,
          },
        },

        price: true,
        productId: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OrderItemLedger",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [OrderItemLedger] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(OrderItemLedgerFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<OrderItemLedger[]> {
    const args = plainToClass(OrderItemLedgerFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        orderId: true,

        orderItem: {
          select: {
            id: true,
          },
        },

        price: true,
        productId: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OrderItemLedger",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OrderItemLedger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: OrderItemLedgerWhereUniqueInput
  ): Promise<OrderItemLedger | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        orderId: true,

        orderItem: {
          select: {
            id: true,
          },
        },

        price: true,
        productId: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OrderItemLedger",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OrderItemLedger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: OrderItemLedgerWhereUniqueInput,
    @common.Body() data: OrderItemLedgerUpdateInput
  ): Promise<OrderItemLedger | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          orderItem: {
            connect: data.orderItem,
          },
        },
        select: {
          amount: true,
          createdAt: true,
          id: true,
          orderId: true,

          orderItem: {
            select: {
              id: true,
            },
          },

          price: true,
          productId: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "OrderItemLedger",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OrderItemLedger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: OrderItemLedgerWhereUniqueInput
  ): Promise<OrderItemLedger | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,
          orderId: true,

          orderItem: {
            select: {
              id: true,
            },
          },

          price: true,
          productId: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
